apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dolos-publisher.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dolos-publisher.labels" . | nindent 4 }}
data:
  dolos.toml: |
    {{- required "dolosToml is required" .Values.dolosToml | nindent 4 }}
